# Generated by Django 5.1.1 on 2024-09-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_jersey_delete_moodentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='jersey',
            name='quantity',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
