# Generated by Django 5.1.1 on 2024-09-16 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20240916_1706'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jersey',
        ),
    ]
