# Generated by Django 5.1.1 on 2024-09-17 07:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_jersey'),
    ]

    operations = [
        migrations.AddField(
            model_name='newjersey',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
